from .BackgroundColor3bit import BackgroundColor3bit as BackgroundColor3bit
from .BackgroundColor8bit import BackgroundColor8bit as BackgroundColor8bit
from .BackgroundColor24bit import BackgroundColor24bit as BackgroundColor24bit
