from .ForegroundColor3bit import ForegroundColor3bit as ForegroundColor3bit
from .ForegroundColor8bit import ForegroundColor8bit as ForegroundColor8bit
from .ForegroundColor24bit import ForegroundColor24bit as ForegroundColor24bit
